### ISSUE TITLE
The latest version is not available in Chocolatey.

### ISSUE THREAD

**Issue by jmatias** [Cirzen/choco-jetbrainsmono#9]
The package repo points to 2.225, but in Chocolatey the latest published version is 2.002

https://github.com/Cirzen/choco-jetbrainsmono/blob/1346800ee4256ea2300a41e35e08f9ae93a5f9b0/tools/chocolateyinstall.ps1#L10-L12

https://github.com/Cirzen/choco-jetbrainsmono/blob/1346800ee4256ea2300a41e35e08f9ae93a5f9b0/jetbrainsmono.nuspec#L29

![image](https://user-images.githubusercontent.com/1302269/149475887-5541f1bc-f503-4ae4-a3e8-24a2d3ea9fc8.png)

**Comment by yeurch** [comment]
Thanks for updating this repo to the latest version, 2.304.  However, the original issue description isn't that this repo is out of date, it's that the [package on the Chocolatey community repo](https://community.chocolatey.org/packages/jetbrainsmono) is out of date, and _still_ points to 2.002.

Please can we re-open this issue, and please can you push the latest version of the package up to Chocolatey?

Thanks in advance!
